- leafletOsmId: "Mapnik"
  code: "M"
  layerId: "mapnik"
  nameId: "standard"
  canEmbed: true
  canDownloadImage: true
  credit:
    id: "make_a_donation"
    href: "https://supporting.openstreetmap.org"
    donate: true
