- leafletOsmId: "Orthophoto"
  url: "http://192.168.1.115:8080/services/zvartnoc_2003_02/tiles/{z}/{x}/{y}.png"
  pane: "timelinePane"
  code: "X"
  year: "2003"
  layerId: "plan_2003_02"
  nameId: "plan"
  canEmbed: true
  canDownloadImage: true
  credit:
    id: "make_a_donation"
    href: "https://supporting.openstreetmap.org"
    donate: true

- leafletOsmId: "Orthophoto"
  url: "http://192.168.1.115:8080/services/zvartnoc_2011_09/tiles/{z}/{x}/{y}.png"
  pane: "timelinePane"
  code: "X"
  year: "2011"
  layerId: "plan_2011_09"
  nameId: "plan"
  canEmbed: true
  canDownloadImage: true
  credit:
    id: "make_a_donation"
    href: "https://supporting.openstreetmap.org"
    donate: true

- leafletOsmId: "Orthophoto"
  url: "http://192.168.1.115:8080/services/zvartnoc_2xxx2_xx/tiles/{z}/{x}/{y}.png"
  pane: "timelinePane"
  code: "X"
  year: "__/__"
  layerId: "plan__/__"
  nameId: "plan"
  canEmbed: true
  canDownloadImage: true
  credit:
    id: "make_a_donation"
    href: "https://supporting.openstreetmap.org"
    donate: true

- leafletOsmId: "Orthophoto"
  url: "http://192.168.1.115:8080/services/zvartnoc_2xxx_xx/tiles/{z}/{x}/{y}.png"
  pane: "timelinePane"
  code: "X"
  year: "__/__"
  layerId: "plan__/__2"
  nameId: "plan"
  canEmbed: true
  canDownloadImage: true
  credit:
    id: "make_a_donation"
    href: "https://supporting.openstreetmap.org"
    donate: true